/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimoniesRouteImport } from './routes/testimonies'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as PrayerRouteImport } from './routes/prayer'
import { Route as GiveRouteImport } from './routes/give'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DevotionalRouteImport } from './routes/devotional'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TestimoniesRoute = TestimoniesRouteImport.update({
  id: '/testimonies',
  path: '/testimonies',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerRoute = PrayerRouteImport.update({
  id: '/prayer',
  path: '/prayer',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveRoute = GiveRouteImport.update({
  id: '/give',
  path: '/give',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DevotionalRoute = DevotionalRouteImport.update({
  id: '/devotional',
  path: '/devotional',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/devotional': typeof DevotionalRoute
  '/gallery': typeof GalleryRoute
  '/give': typeof GiveRoute
  '/prayer': typeof PrayerRoute
  '/programs': typeof ProgramsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonies': typeof TestimoniesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/devotional': typeof DevotionalRoute
  '/gallery': typeof GalleryRoute
  '/give': typeof GiveRoute
  '/prayer': typeof PrayerRoute
  '/programs': typeof ProgramsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonies': typeof TestimoniesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/devotional': typeof DevotionalRoute
  '/gallery': typeof GalleryRoute
  '/give': typeof GiveRoute
  '/prayer': typeof PrayerRoute
  '/programs': typeof ProgramsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonies': typeof TestimoniesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/devotional'
    | '/gallery'
    | '/give'
    | '/prayer'
    | '/programs'
    | '/sitemap.xml'
    | '/testimonies'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/devotional'
    | '/gallery'
    | '/give'
    | '/prayer'
    | '/programs'
    | '/sitemap.xml'
    | '/testimonies'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/devotional'
    | '/gallery'
    | '/give'
    | '/prayer'
    | '/programs'
    | '/sitemap.xml'
    | '/testimonies'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DevotionalRoute: typeof DevotionalRoute
  GalleryRoute: typeof GalleryRoute
  GiveRoute: typeof GiveRoute
  PrayerRoute: typeof PrayerRoute
  ProgramsRoute: typeof ProgramsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TestimoniesRoute: typeof TestimoniesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonies': {
      id: '/testimonies'
      path: '/testimonies'
      fullPath: '/testimonies'
      preLoaderRoute: typeof TestimoniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer': {
      id: '/prayer'
      path: '/prayer'
      fullPath: '/prayer'
      preLoaderRoute: typeof PrayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/give': {
      id: '/give'
      path: '/give'
      fullPath: '/give'
      preLoaderRoute: typeof GiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devotional': {
      id: '/devotional'
      path: '/devotional'
      fullPath: '/devotional'
      preLoaderRoute: typeof DevotionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DevotionalRoute: DevotionalRoute,
  GalleryRoute: GalleryRoute,
  GiveRoute: GiveRoute,
  PrayerRoute: PrayerRoute,
  ProgramsRoute: ProgramsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TestimoniesRoute: TestimoniesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
